version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 3
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: UTC
    open-pull-requests-limit: 3
    groups:
      nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
