using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using ClosedXML.Excel;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Win7POS.Core.Import;
using Win7POS.Core.Models;
using Win7POS.Data.Import;

namespace Win7POS.Core.Tests.Import;

[TestClass]
[DoNotParallelize]
public sealed class SupplierExcelImportReaderParityTests
{
    // Upstream ExcelDataReader MIT test fixtures, pinned by git blob SHA:
    // https://github.com/ExcelDataReader/ExcelDataReader/blob/develop/src/TestData/10x10.xls
    // https://github.com/ExcelDataReader/ExcelDataReader/blob/develop/src/TestData/Issue301_IgnoreCase.xlsx
    private const string RealBinaryXlsBase64 =
            "0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAAGQAAAAAAAAAAEAAA/v///wAAAAD+////AAAAABgAAAD/////////////" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////" +
            "//////////////////////////////////////////////////////////////////////////////////8JCBAAAAYFAOwVzQfJwAAABgMAAOEAAgCwBMEA" +
            "AgAAAOIAAABcAHAADwAASm9oYW4gQXBwZWxncmVuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
            "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEIAAgCwBGEBAgAAAMABAAA9AQIAAQCcAAIADgAZAAIAAAASAAIAAAATAAIAAACvAQIAAAC8AQIA" +
            "AAA9ABIAeAB4AB87VCQ4AAAAAAABAFgCQAACAAAAjQACAAAAIgACAAAADgACAAEAtwECAAAA2gACAAAAMQAaAMgAAAD/f5ABAAAAAAD8BQFBAHIAaQBhAGwA" +
            "MQAaAMgAAAD/f5ABAAAAAAD8BQFBAHIAaQBhAGwAMQAaAMgAAAD/f5ABAAAAAAD8BQFBAHIAaQBhAGwAMQAaAMgAAAD/f5ABAAAAAAD8BQFBAHIAaQBhAGwA" +
            "MQAaAKAAAAD/f5ABAAAAAAD8BQFBAHIAaQBhAGwAHgQrAAUAEwABIwAsACMAIwAwACIArCAiADsAXAAtACMALAAjACMAMAAiAKwgIgAeBDUABgAYAAEjACwA" +
            "IwAjADAAIgCsICIAOwBbAFIAZQBkAF0AXAAtACMALAAjACMAMAAiAKwgIgAeBDcABwAZAAEjACwAIwAjADAALgAwADAAIgCsICIAOwBcAC0AIwAsACMAIwAw" +
            "AC4AMAAwACIArCAiAB4EQQAIAB4AASMALAAjACMAMAAuADAAMAAiAKwgIgA7AFsAUgBlAGQAXQBcAC0AIwAsACMAIwAwAC4AMAAwACIArCAiAB4EZQAqADAA" +
            "AV8ALQAqACAAIwAsACMAIwAwACIArCAiAF8ALQA7AFwALQAqACAAIwAsACMAIwAwACIArCAiAF8ALQA7AF8ALQAqACAAIgAtACIAIgCsICIAXwAtADsAXwAt" +
            "AEAAXwAtAB4EXwApAC0AAV8ALQAqACAAIwAsACMAIwAwAF8ArCBfAC0AOwBcAC0AKgAgACMALAAjACMAMABfAKwgXwAtADsAXwAtACoAIAAiAC0AIgBfAKwg" +
            "XwAtADsAXwAtAEAAXwAtAB4EdQAsADgAAV8ALQAqACAAIwAsACMAIwAwAC4AMAAwACIArCAiAF8ALQA7AFwALQAqACAAIwAsACMAIwAwAC4AMAAwACIArCAi" +
            "AF8ALQA7AF8ALQAqACAAIgAtACIAPwA/ACIArCAiAF8ALQA7AF8ALQBAAF8ALQAeBG8AKwA1AAFfAC0AKgAgACMALAAjACMAMAAuADAAMABfAKwgXwAtADsA" +
            "XAAtACoAIAAjACwAIwAjADAALgAwADAAXwCsIF8ALQA7AF8ALQAqACAAIgAtACIAPwA/AF8ArCBfAC0AOwBfAC0AQABfAC0AHgQcAKQAFwAAIiQiIywjIzBf" +
            "KTtcKCIkIiMsIyMwXCkeBCEApQAcAAAiJCIjLCMjMF8pO1tSZWRdXCgiJCIjLCMjMFwpHgQiAKYAHQAAIiQiIywjIzAuMDBfKTtcKCIkIiMsIyMwLjAwXCke" +
            "BCcApwAiAAAiJCIjLCMjMC4wMF8pO1tSZWRdXCgiJCIjLCMjMC4wMFwpHgQ3AKgAMgAAXygiJCIqICMsIyMwXyk7XygiJCIqIFwoIywjIzBcKTtfKCIkIiog" +
            "Ii0iXyk7XyhAXykeBC4AqQApAABfKCogIywjIzBfKTtfKCogXCgjLCMjMFwpO18oKiAiLSJfKTtfKEBfKR4EPwCqADoAAF8oIiQiKiAjLCMjMC4wMF8pO18o" +
            "IiQiKiBcKCMsIyMwLjAwXCk7XygiJCIqICItIj8/Xyk7XyhAXykeBDYAqwAxAABfKCogIywjIzAuMDBfKTtfKCogXCgjLCMjMC4wMFwpO18oKiAiLSI/P18p" +
            "O18oQF8p4AAUAAAAAAD1/yAAAAAAAAAAAAAAAMAg4AAUAAEAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAEAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAIAAAD1/yAA" +
            "APQAAAAAAAAAAMAg4AAUAAIAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAA" +
            "AAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAAAAD1/yAAAPQAAAAAAAAAAMAg" +
            "4AAUAAAAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAAAAD1/yAAAPQAAAAAAAAAAMAg4AAUAAAAAAD1/yAAAPQAAAAA" +
            "AAAAAMAg4AAUAAAAAAABACAAAAAAAAAAAAAAAMAg4AAUAAEAqwD1/yAAAPgAAAAAAAAAAMAg4AAUAAEAqQD1/yAAAPgAAAAAAAAAAMAg4AAUAAEAqgD1/yAA" +
            "APgAAAAAAAAAAMAg4AAUAAEAqAD1/yAAAPgAAAAAAAAAAMAg4AAUAAEACQD1/yAAAPgAAAAAAAAAAMAgkwIEABCAA/+TAgQAEYAG/5MCBAASgAT/kwIEABOA" +
            "B/+TAgQAAIAA/5MCBAAUgAX/YAECAAEAhQAOABAJAAAAAAYAU2hlZXQxjAAEAAEAAQDBAQgAwQEAAIA4AQD8ALsARwAAABcAAAAEAABjb2wxBAAAY29sMwQA" +
            "AGNvbDUEAABjb2w3BAAAY29sOQUAADEweDEwBQAAMTB4MTEFAAAxMHgxMgUAADEweDEzBQAAMTB4MTQFAAAxMHgxNQUAADEweDE2BQAAMTB4MTcFAAAxMHgx" +
            "OAUAADEweDE5BQAAMTB4MjAFAAAxMHgyMQUAADEweDIyBQAAMTB4MjMFAAAxMHgyNAUAADEweDI1BQAAMTB4MjYFAAAxMHgyN/8AGgAIACIIAAAMAAAAXQgA" +
            "AEcAAACdCAAAhwAAAGMIFQBjCAAAAAAAAAAAAAAVAAAAAAAAAF4KAAAACQgQAAAGEADsFc0HycAAAAYDAAALAhQAAAAAAAAAAAAKAAAAzAkAAI4OAAANAAIA" +
            "AQAMAAIAZAAPAAIAAQARAAIAAAAQAAgA/Knx0k1iUD9fAAIAAQAqAAIAAAArAAIAAACCAAIAAQCAAAgAAAAAAAAAAAAlAgQAAAD/AIEAAgDBBBQAAAAVAAAA" +
            "gwACAAAAhAACAAAAoQAiAAAA/wABAAEAAQAEAAAAAAAAAAAAAADgPwAAAAAAAOA/AABVAAIACAAAAg4AAAAAAAoAAAAAAAoAAAAIAhAAAAAAAAoA/wAAAAAA" +
            "AAEPAAgCEAABAAAACgD/AAAAAAAAAQ8ACAIQAAIAAAAKAP8AAAAAAAABDwAIAhAAAwAAAAoA/wAAAAAAAAEPAAgCEAAEAAAACgD/AAAAAAAAAQ8ACAIQAAUA" +
            "AAAKAP8AAAAAAAABDwAIAhAABgAAAAoA/wAAAAAAAAEPAAgCEAAHAAAACgD/AAAAAAAAAQ8ACAIQAAgAAAAKAP8AAAAAAAABDwAIAhAACQAAAAoA/wAAAAAA" +
            "AAEPAP0ACgAAAAAADwAAAAAA/QAKAAAAAgAPAAEAAAD9AAoAAAAEAA8AAgAAAP0ACgAAAAYADwADAAAA/QAKAAAACAAPAAQAAAD9AAoAAQAAAA8ABQAAAP0A" +
            "CgABAAkADwAOAAAA/QAKAAIAAAAPAAYAAAD9AAoAAgABAA8ABwAAAP0ACgACAAIADwAIAAAA/QAKAAIAAwAPAAkAAAD9AAoAAgAEAA8ACgAAAP0ACgACAAUA" +
            "DwALAAAA/QAKAAIABgAPAAwAAAD9AAoAAgAHAA8ADQAAAP0ACgACAAgADwAOAAAA/QAKAAIACQAPAA8AAAD9AAoAAwAAAA8ABwAAAP0ACgADAAkADwAQAAAA" +
            "/QAKAAQAAAAPAAgAAAD9AAoABAABAA8ACQAAAP0ACgAEAAIADwAKAAAA/QAKAAQAAwAPAAsAAAD9AAoABAAEAA8ADAAAAP0ACgAEAAUADwANAAAA/QAKAAQA" +
            "BgAPAA4AAAD9AAoABAAHAA8ADwAAAP0ACgAEAAgADwAQAAAA/QAKAAQACQAPABEAAAD9AAoABQAAAA8ACQAAAP0ACgAFAAEADwAKAAAA/QAKAAUAAgAPAAsA" +
            "AAD9AAoABQADAA8ADAAAAP0ACgAFAAQADwANAAAA/QAKAAUABQAPAA4AAAD9AAoABQAGAA8ADwAAAP0ACgAFAAcADwAQAAAA/QAKAAUACAAPABEAAAD9AAoA" +
            "BQAJAA8AEgAAAP0ACgAGAAAADwAKAAAA/QAKAAYACQAPABMAAAD9AAoABwAAAA8ACwAAAP0ACgAHAAEADwAMAAAA/QAKAAcAAgAPAA0AAAD9AAoABwADAA8A" +
            "DgAAAP0ACgAHAAQADwAPAAAA/QAKAAcABQAPABAAAAD9AAoABwAGAA8AEQAAAP0ACgAHAAcADwASAAAA/QAKAAcACAAPABMAAAD9AAoABwAJAA8AFAAAAP0A" +
            "CgAIAAAADwAMAAAA/QAKAAgAAQAPAA0AAAD9AAoACAACAA8ADgAAAP0ACgAIAAMADwAPAAAA/QAKAAgABAAPABAAAAD9AAoACAAFAA8AEQAAAP0ACgAIAAYA" +
            "DwASAAAA/QAKAAgABwAPABMAAAD9AAoACAAIAA8AFAAAAP0ACgAIAAkADwAVAAAA/QAKAAkAAAAPAA0AAAD9AAoACQABAA8ADgAAAP0ACgAJAAIADwAPAAAA" +
            "/QAKAAkAAwAPABAAAAD9AAoACQAEAA8AEQAAAP0ACgAJAAUADwASAAAA/QAKAAkABgAPABMAAAD9AAoACQAHAA8AFAAAAP0ACgAJAAgADwAVAAAA/QAKAAkA" +
            "CQAPABYAAADXABgAqgQAALQARgAcAIwAHACMAIwAHACMAIwAPgISALYGAAAAAEAAAAAAAAAAAAAAAB0ADwADAAAJAAAAAQAAAAAACQnvAAYABQA3AAAACgAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAA/v8AAAUBAgAAAAAAAAAAAAAAAAAAAAAAAQAAAOCFn/L5T2gQq5EIACsns9kwAAAAnAAAAAcAAAABAAAAQAAAAAQAAABIAAAA" +
            "CAAAAFQAAAASAAAAZAAAAAwAAAB8AAAADQAAAIgAAAATAAAAlAAAAAIAAADkBAAAHgAAAAQAAAAAAAAAHgAAAAgAAAB1c2VyAAAAAB4AAAAQAAAATWljcm9z" +
            "b2Z0IEV4Y2VsAEAAAAAAlPgZKLq7AUAAAACAMoP5Iy3JAQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7/AAAFAQIAAAAAAAAAAAAAAAAAAAAAAAEA" +
            "AAAC1c3VnC4bEJOXCAArLPmuMAAAAMQAAAAJAAAAAQAAAFAAAAAPAAAAWAAAABcAAABkAAAACwAAAGwAAAAQAAAAdAAAABMAAAB8AAAAFgAAAIQAAAANAAAA" +
            "jAAAAAwAAACfAAAAAgAAAOQEAAAeAAAABAAAAAAAAAADAAAA5hULAAsAAAAAAAAACwAAAAAAAAALAAAAAAAAAAsAAAAAAAAAHhAAAAEAAAAHAAAAU2hlZXQx" +
            "AAwQAAACAAAAHgAAAAsAAABXb3Jrc2hlZXRzAAMAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAgAAAAMAAAAEAAAABQAAAAYAAAAHAAAA/v///wkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAD+////EQAAABIA" +
            "AAATAAAAFAAAABUAAAAWAAAAFwAAAP7////9/////v//////////////////////////////////////////////////////////////////////////////" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////" +
            "/////////////////////////////////////////////////////////////////////////////////////////////////////////////1IAbwBvAHQA" +
            "IABFAG4AdAByAHkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUB//////////8CAAAAIAgCAAAAAADAAAAAAAAARgAA" +
            "AAAAAAAAAAAAAJAqveYJyNwB/v///wAAAAAAAAAAVwBvAHIAawBiAG8AbwBrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAABIAAgH///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAFAFMAdQBtAG0AYQByAHkASQBuAGYA" +
            "bwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAACAQEAAAADAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAgAAAAAEAAAAAAAAAUARABvAGMAdQBtAGUAbgB0AFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAA4AAIB////////" +
            "////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAA";

    private const string ClosedXmlFallbackXlsxBase64 =
            "UEsDBBQABgAIAAAAIQDretKTYgEAAJAEAAATANwBW0NvbnRlbnRfVHlwZXNdLnhtbCCi2AEooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArFTLTsMwELwj8Q+Rryhx" +
            "ywEh1LQHHkeoBHyAsTeNVce2vNvS/j2bhFaASqSqvSSKop2ZnRl7Mts0LltDQht8KcbFSGTgdTDWL0rx/vaU34oMSXmjXPBQii2gmE0vLyZv2wiY8bTHUtRE" +
            "8U5K1DU0CosQwfOfKqRGEX+mhYxKL9UC5PVodCN18ASecmoxxHTywgKSNZDNVaJn1TCP3DhJjAb9c1wwnsju+8GWuxQqRme1IlYu1978Yc1DVVkNJuhVw1xF" +
            "B3bVosh/CZG2DvBkKowJlMEagBpX9KA75geo1MpR9rhhB3rTEzg8brVvMwue7NbH2kYcYBj2btiTz5CWHyEsz+1K607RKOt3ug+VgNObpxBRctYnC4DWcgMm" +
            "jwwJiSzsPTvEzQVsd+9iRNm9Tm/h72rs8Yc8YB1YqwTmlRKfyrPX8yf2kI59FjokOD6MXWfb6QMJyO4+mX4BAAD//wMAUEsDBBQABgAIAAAAIQC1VTAj9QAA" +
            "AEwCAAALAM4BX3JlbHMvLnJlbHMgosoBKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMks9OwzAMxu9IvEPk++puSAihpbtMSLshVB7AJO4ftY2jJED39oQDgkpj29H2588/W97u5mlUHxxi" +
            "L07DuihBsTNie9dqeK2fVg+gYiJnaRTHGo4cYVfd3mxfeKSUm2LX+6iyi4saupT8I2I0HU8UC/HscqWRMFHKYWjRkxmoZdyU5T2Gvx5QLTzVwWoIB3sHqj76" +
            "PPmytzRNb3gv5n1il06MQJ4TO8t25UNmC6nP26iaQstJgxXznNMRyfsiYwOeJtpcT/T/tjhxIkuJ0Ejg8zzfinNA6+uBLp9oqfi9zjzip4ThTWT4YcHFD1Rf" +
            "AAAA//8DAFBLAwQUAAIACAAAACEAgT6Ul+wAAAC6AgAAGgAAAHhsL19yZWxzL1dvcmtCb29rLnhtbC5yZWxzrVLLasMwELwX+g9i77XstJRSIucSCrm27gcI" +
            "aW2Z2JLQbh/++6oNbRwIoQeflhmxM6PdXW8+x0G8Y6I+eAVVUYJAb4LtfafgtXm6eQBBrL3VQ/CoYEKCTX19tX7GQXNuItdHElnFkwLHHB+lJONw1FSEiD6/" +
            "tCGNmjNMnYza7HWHclWW9zLNNaA+0RQ7qyDt7C2IZor4H+3Qtr3BbTBvI3o+YyGJpyF/QDQ6dcgKDrjIOiDP26+WtOfci0f3H3ggq0sZqiUzfIS0J4fIxxx/" +
            "VB7Qd7kY5m7RfTid0L5wyuc2X8uc/g0jTy6u/gJQSwMEFAACAAgAAAAhAAVe6GQ/AQAAFAIAAA8AAAB4bC9Xb3JrQm9vay54bWyNkU1PwzAMhu9I/IfId9av" +
            "dcC0dhICxC4IibGdQ+Ou0dKkSjK6/XucTh1w42S/jv3otbNYHlvFvtA6aXQBySQGhroyQupdAR/r55s7YM5zLbgyGgs4oYNleX216I3dfxqzZwTQroDG+24e" +
            "Ra5qsOVuYjrU9FIb23JP0u4i11nkwjWIvlVRGsezqOVSw5kwt/9hmLqWFT6a6tCi9meIRcU92XeN7ByUi1oq3Jw3YrzrXnlLvo8KmOLOPwnpURQwJWl6/FOw" +
            "h+7hIFUQeZxDVF6WfLNMYM0Pyq/J2kine6XTNJ2FztC1kdi7n6Eg2XErtTB9AVlGpz2N6jYH1g/5VgrfEClPskvtBeWu8QXcZ3Ec4NEv+nC/MTI9LPce8oQ+" +
            "KsQV+afcziUldiWSgTCOVVxVtE0IQ2M6zZP7oWO0XX4DUEsDBBQAAgAIAAAAIQCZdeFs3wAAAIACAAAUAAAAeGwvU2hhcmVkU3RyaW5ncy54bWxt0sFKxDAQ" +
            "gOG74DuEubtJZnV3lSR7EHwCfYDQxm2gSWonlfXtbRBE7BznCyHzQ8z5mkbxGWaKJVvQOwUi5K70MV8svL2+3J1AUPW592PJwcJXIDi72xtDVMV6N5OFodbp" +
            "SUrqhpA87coU8nryXubk6zrOF0nTHHxPQwg1jRKVOsjkYwbRlSVXC0cNYsnxYwnPP4B7cIaiM9V1ZdRGVmdkm39tz9gDY0fGHv+bVletONy83BA53OzT8J7D" +
            "zZYNDxxudm944pArQq4IuSLkipArQq4IuSLkivBPkVx/kPsGUEsDBBQAAgAIAAAAIQDKZ7koegEAAFcDAAANAAAAeGwvU1RZTEVTLlhNTKWTyWrDMBCG74W+" +
            "g9C9kRNoSIvt0Eug0JZCUuhViWRboMVI45D06TvyEsdQ2kNPmuWfb0YaO12fjCZH6YNyNqPzWUKJtAcnlC0z+rHb3K0oCcCt4NpZmdGzDHSd396kAc5abisp" +
            "gSDChoxWAPUjY+FQScPDzNXSYqZw3nBA15cs1F5yEWKR0WyRJEtmuLI0TwtnIZCDayxkdNEH8jR8kSPXOFdCWZ5abmTnP3nFdQyxTjdVr34Xt0fAIqX1tCcG" +
            "8rTmANLbDTqkt3fnGq9u8QE6TKv7Q116fp4v7q8K2gP77p0X+OBD5zkdQnmqZQFY4FVZxRNczWISwBk0hOKls1xH5FDRG4g9SK23cSmfxYR9KohtzMbAs8go" +
            "rjfefjBxoN7sMJ0T+de0jv1vLDkVU/4F3Taa0C9REveY0bf4FekRQfaN0qDsDwMjU5zGWdss8D1+rJMuyBCy4I2G3SWZ0dF+lUI15uGieldHB71qtF/ipubL" +
            "doLxj8i/AVBLAwQUAAIACAAAACEA6aYluLIFAABTGwAAEwAAAHhsL3RoZW1lL3RoZW1lMS54bWztWU2P20QYviPxH0a+t44TO82umq022aSFdtvVblrU48SZ" +
            "2NOMPdbMZLe5ofaIhIQoiAsSNw4IqNRKXMqvWSiCIvUv8PojyXgz3mbbRRS1OSSe8fN+f/gd5/KV+xFDh0RIyuO25VysWYjEPh/ROGhbtwf9Cy0LSYXjEWY8" +
            "Jm1rRqR1ZevDDy7jTRWSiCCgj+UmbluhUsmmbUsftrG8yBMSw70xFxFWsBSBPRL4CPhGzK7Xak07wjS2UIwjYHtrPKY+QYOUpbU1Z95j8BUrmW74TBz4mUSd" +
            "IsOOJk76I2eyywQ6xKxtgZwRPxqQ+8pCDEsFN9pWLftY9tZle0HEVAWtRtfPPgVdQTCa1DM6EQwXhE7f3bi0s+Bfz/mv4nq9XrfnLPhlAOz7YKmzgnX7Lacz" +
            "56mB8stV3t2aV3PLeI1/YwW/0el0vI0SvrHEuyv4Vq3pbtdLeHeJ91b172x3u80S3lvimyv4/qWNplvGZ6CQ0Xiygk7juYjMAjLm7JoR3gJ4a54AS5StZVdO" +
            "H6uqXIvwPS76AMiCixWNkZolZIx9wHVxNBQUpwLwJsHanXzLlytbqSwkfUET1bY+TjBUxBLy8tmPL589QS+fPT5+8PT4wS/HDx8eP/jZQHgNx4FO+OL7L/7+" +
            "9lP015PvXjz6yoyXOv73nz777dcvzUClA59//fiPp4+ff/P5nz88MsC3BR7q8AGNiEQ3yRHa5xHYZhBAhuJsFIMQ0xIFDgFpAPZUWALenGFmwnVI2Xl3BDQA" +
            "E/Dq9F5J14NQTBU1AK+HUQm4yznrcGE053oqSzdnGgdm4WKq4/YxPjTJ7p4IbW+aQCZTE8tuSEpq7jGINg5ITBRK7/EJIQayu5SW/LpLfcElHyt0l6IOpkaX" +
            "DOhQmYmu0QjiMjMpCKEu+Wb3DupwZmK/Qw7LSCgIzEwsCSu58SqeKhwZNcYR05E3sApNSh7MhF9yuFQQ6YAwjnojIqWJ5paYldS9jqETGcO+y2ZRGSkUnZiQ" +
            "NzDnOnKHT7ohjhKjzjQOdexHcgIpitEeV0YleLlC0jXEAceV4b5DiTpbWd+mQWhOkPTOVBRdu9R/Ixqf1owZhW78vhnP4dvwaDKVxMkWXIX7HzbeHTyN9wjk" +
            "+vu++77vvot9t6qW1+22ywZr63Nxxi+qHJLHlLEDNWPkhsxaswSlR33YzBYZ0WImT0K4LMSVcIHA2TUSXH1CVXgQ4gTEOJmEQBasA4kSLuEkYFXyzo6TFIzP" +
            "9rz5GRDQWO3yUb7d0M+GCzbZKpC6oEbKYF1hjUtvJszJgWtKczyzNO9UabbmTagGhNOTv9Os56IhYzAjo9TvOYN5WM49RDLEI1LEyDEa4jTWdFvr1V7TpG00" +
            "3kzaOkHSxbkV4rxziFJtJUr2ajmyuLxCR6CVV/cs5OOkbY1hkoLLKAF+Mm1AmAVx2/JVYcori/mkwea0dGqVBpdEJEKqHSzDnCq7NX91Ei/1r3tu6ofzMcDQ" +
            "jdbTotFy/kMt7JOhJeMx8VXFznJZ3ONTRcRBODpCQzYV+xj0dvPsGlEJz4z6fCGgQt0i8cqVX1TByVc0RXVgloS46EktLfY5PLte6JCtNPXsCt1f05TGOZri" +
            "vbumpJkLY2tjlB2oYAwQGKU52ra4UCGHLpSE1O8LGBwyWaAXgrJIVUIsfeGc6koOl30r55E3uSBU+zRAgkKnU6EgZE8Vdr6CmVPXn69zRkWfWagrk/x3SA4J" +
            "G6TV20ztt1A47yaFIzLcyaDZpuoaBv23ePJxKyaf08eDpSD3LLOIqzV97VGw8WYqnPFRWzdbXPfWftQmcPhA6Rc0bip8tpxvB3wfoo8WEyWCRLzQKspvsTkE" +
            "nVuacSmrf3eMWoagVRHv8xw+NWc3Kpx9urjXd7Zn8LV3uqvt1RK1tYNMtlr544kP74HsHTgoTZmS+duk+3DU7M7/MgA+9pJ06x9QSwMEFAACAAgAAAAhAJSx" +
            "HafaAgAAiwsAABgAAAB4bC9Xb3JrU2hlZXRzL1NIRUVUMS54bWyN1l2PojAUBuD7TfY/EO53+HBAMOpkBEFNNtns53UHi5CBlqUd3fn3U2DGtE092SuBF96W" +
            "xxjP8uFf21hn3LOakpXt3bm2hUlBjzU5rexfP7MvkW0xjsgRNZTglf2Kmf2w/vxpeaH9M6sw5pZoIGxlV5x3C8dhRYVbxO5oh4lIStq3iIvT/uSwrsfoOD7U" +
            "No7vuqHToprYU8Oi/58OWpZ1gVNavLSY8Kmkxw3iYv+sqjtmr5fHWmTDC1k9Llf2o7c4eK7trJfj0r9rfGHSscXR0w/c4ILjoxCwreHNnih9HsK9uOSKSjbe" +
            "MFQi8XHGCW6alX0Qd7O/4yLiUCzgXFvl44/VsvE9vvXWEZfopeHf6WWH61PFxbL+3Ty4bjFFHK2XPb1Y/bgj1qFB2Ft4w16K4eqjuCyeG173vHaXzlksWLxn" +
            "iZx5araVM1/Ncjmbqdlezu6vmSM2ed2pb96pLz0ZqK0HOfNu1M7MtTPp0VCt3cjZXMORs0jNUjmLNTg58zTxTAk18lwJNfOdEuroMzPPZKeEgdnu3mx3f9vn" +
            "IGdeaK4NzLXBbdpNcJs2CQDaNABotwFAmwUAbR4AtLvATDt9KYEZaNJTwrlZLzTrhbeFNiEglISAUBoCQtsQEMpCQCgPAaFdCAjtQ7PQxKeEkZlvbuabA0QH" +
            "JYzNvZG5NwJ0NxGgm0SAbhoButsI0M0iQDePAN1dZNadvpfITDT5yaHvmv1is18MEG1igCiJAaI0Boi2MUCUxQBRHgNEuxgg2sdmoslPCT2znzAz/9O7ANJG" +
            "TTWlRE01plRNNaetmmpQmZpqUrmaalQ7JdWt9mqq/eIOauprlI40P3WVmFh5XYiBq6SE76fpjr92YowlNKHkfewdxq4OnfBX1J9qwqwGl2IBdxjIrH4az6YT" +
            "Trux4olyTtvxsBIDLe6HG0ReUso/TkTnlGXjRQs19Yn8qXn1vsowVg4D43WMXr8BUEsDBBQABgAIAAAAIQCippBnSwEAAFgCAAARAAgBZG9jUHJvcHMvY29y" +
            "ZS54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8" +
            "klFLwzAUhd8F/0PJe5tkdcWFtgOV4YMDwYriW0jutmKTliSz2783bbdamfh4c8797rmXpMuDqoIvMLasdYZoRFAAWtSy1NsMvRar8BYF1nEteVVryNARLFrm" +
            "11epaJioDTybugHjSrCBJ2nLRJOhnXMNw9iKHShuI+/QXtzURnHnS7PFDReffAt4RkiCFTguueO4A4bNSEQnpBQjstmbqgdIgaECBdpZTCOKf7wOjLJ/NvTK" +
            "xKlKd2z8Tqe4U7YUgzi6D7YcjW3bRm3cx/D5KX5fP730q4al7m4lAOWpFEwY4K42eYqnhT9cxa1b+xtvSpB3x/xxr7gmNMWXksf0qQcWyMDnYEPqs/IW3z8U" +
            "K5TTxSIJKQnpTTGLWRyz2e1HN/lXf5dreFCn+f8Q/XKLkMxDSguaMDJnJJkQzwC/3sVfyL8BAAD//wMAUEsDBBQABgAIAAAAIQAnOIvEiAEAABEDAAAQAAgB" +
            "ZG9jUHJvcHMvYXBwLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAJySwW7bMAyG7wP2DobujZxgGIZAVlGkHXrYsABJu7Mm07FQWRJE1kj29KNtpHG6naYTyZ/49YmUuj12vugho4uhEstFKQoINtYuHCrxtP96" +
            "80UUSCbUxscAlTgBilv98YPa5pggkwMs2CJgJVqitJYSbQudwQXLgZUm5s4Qp/kgY9M4C/fRvnYQSK7K8rOEI0Goob5Jb4Ziclz39L+mdbQDHz7vT4mBtbpL" +
            "yTtriF+pvzubI8aGioejBa/kXFRMtwP7mh2ddKnkPFU7azxs2Fg3xiMoeSmoRzDD0LbGZdSqp3UPlmIu0P3msa1E8csgDDiV6E12JhBjDW1TMsY+IWX9M+YX" +
            "bAEIleSGqTiG89557D7p5djAwXXjYDCBsHCNuHfkAX80W5PpH8TLOfHIMPFOOLuBb7pzzjc+mW96572JXTLhxMJb9M2FF3xK+3hvCM7jvC6qXWsy1LyBs34p" +
            "qEeeZPaDyaY14QD1uedvYVj+8/TD9XK1KPmMOz/XlLz8Zf0HAAD//wMAUEsDBBQAAgAAAJK9j0sAAAAAAAAAAAAAAAADAAAAeGwvUEsDBBQAAgAAAHu9j0sA" +
            "AAAAAAAAAAAAAAAJAAAAeGwvdGhlbWUvUEsDBBQAAgAAAJS9j0sAAAAAAAAAAAAAAAAOAAAAeGwvV29ya1NoZWV0cy9QSwMEFAACAAAApb2PSwAAAAAAAAAA" +
            "AAAAAAkAAAB4bC9fcmVscy9QSwECLQAUAAYACAAAACEA63rSk2IBAACQBAAAEwAAAAAAAAAAAAAAAAAAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQItABQA" +
            "BgAIAAAAIQC1VTAj9QAAAEwCAAALAAAAAAAAAAAAAAAAAG8DAABfcmVscy8ucmVsc1BLAQIUABQAAgAIAAAAIQCBPpSX7AAAALoCAAAaAAAAAAAAAAEAIAAA" +
            "AFsGAAB4bC9fcmVscy9Xb3JrQm9vay54bWwucmVsc1BLAQIUABQAAgAIAAAAIQAFXuhkPwEAABQCAAAPAAAAAAAAAAEAIAAAAH8HAAB4bC9Xb3JrQm9vay54" +
            "bWxQSwECFAAUAAIACAAAACEAmXXhbN8AAACAAgAAFAAAAAAAAAABACAAAADrCAAAeGwvU2hhcmVkU3RyaW5ncy54bWxQSwECFAAUAAIACAAAACEAyme5KHoB" +
            "AABXAwAADQAAAAAAAAABACAAAAD8CQAAeGwvU1RZTEVTLlhNTFBLAQIUABQAAgAIAAAAIQDppiW4sgUAAFMbAAATAAAAAAAAAAEAIAAAAKELAAB4bC90aGVt" +
            "ZS90aGVtZTEueG1sUEsBAhQAFAACAAgAAAAhAJSxHafaAgAAiwsAABgAAAAAAAAAAQAgAAAAhBEAAHhsL1dvcmtTaGVldHMvU0hFRVQxLnhtbFBLAQItABQA" +
            "BgAIAAAAIQCippBnSwEAAFgCAAARAAAAAAAAAAAAAAAAAJQUAABkb2NQcm9wcy9jb3JlLnhtbFBLAQItABQABgAIAAAAIQAnOIvEiAEAABEDAAAQAAAAAAAA" +
            "AAAAAAAAABYXAABkb2NQcm9wcy9hcHAueG1sUEsBAhQAFAACAAAAkr2PSwAAAAAAAAAAAAAAAAMAAAAAAAAAAAAQAAAA1BkAAHhsL1BLAQIUABQAAgAAAHu9" +
            "j0sAAAAAAAAAAAAAAAAJAAAAAAAAAAAAEAAAAPUZAAB4bC90aGVtZS9QSwECFAAUAAIAAACUvY9LAAAAAAAAAAAAAAAADgAAAAAAAAAAABAAAAAcGgAAeGwv" +
            "V29ya1NoZWV0cy9QSwECFAAUAAIAAAClvY9LAAAAAAAAAAAAAAAACQAAAAAAAAAAABAAAABIGgAAeGwvX3JlbHMvUEsFBgAAAAAOAA4AWwMAAG8aAAAAAA==";
    [TestMethod]
    public void ReadFirstWorksheet_XlsxSemanticCorpus_PreservesBaseline()
    {
        using var culture = new CultureScope(CultureInfo.InvariantCulture);
        var path = TempPath(".xlsx");
        try
        {
            WriteSemanticWorkbook(path);

            Assert.AreEqual(2, SupplierExcelImportReader.CountWorksheets(path));
            var table = SupplierExcelImportReader.ReadFirstWorksheet(path);

            Assert.AreEqual("Semantic First", table.SheetName);
            Assert.IsTrue(table.HasHeader);
            Assert.AreEqual(3, table.DataRowIndex);
            Assert.AreEqual(1, table.DroppedSummaryRows);
            Assert.AreEqual(12, table.Columns.Count);
            CollectionAssert.AreEqual(
                new[]
                {
                    AndroidImportKeys.Barcode,
                    AndroidImportKeys.ItemNumber,
                    AndroidImportKeys.ProductName,
                    AndroidImportKeys.SecondProductName,
                    AndroidImportKeys.PurchasePrice,
                    AndroidImportKeys.RetailPrice,
                    AndroidImportKeys.Quantity,
                    AndroidImportKeys.Supplier,
                    AndroidImportKeys.Category,
                    AndroidImportKeys.TotalPrice,
                    string.Empty,
                    string.Empty
                },
                table.Columns.Select(column => column.CanonicalKey).ToArray());
            Assert.IsTrue(table.Columns.Take(10).All(column => column.HeaderSource == "alias"));
            Assert.IsTrue(table.Columns.Skip(10).All(column => column.HeaderSource == "unknown"));

            Assert.AreEqual(5, table.Rows.Count);
            CollectionAssert.AreEqual(new[] { 4, 5, 6, 7, 9 }, table.Rows.Select(row => row.RowNumber).ToArray());
            Assert.AreEqual("00123456", table.Rows[0].Values[0], "Formatted leading-zero barcode changed.");
            Assert.AreEqual("1234.56", table.Rows[0].Values[4]);
            Assert.AreEqual("2469.12", table.Rows[0].Values[9], "Formatted decimal changed.");
            Assert.AreEqual("TRUE", table.Rows[0].Values[10], "Boolean formatting changed.");
            Assert.AreEqual("2026-08-02", table.Rows[0].Values[11], "Date formatting changed.");
            Assert.AreEqual("1.234,56", table.Rows[1].Values[4]);
            Assert.AreEqual("1,234.56", table.Rows[1].Values[5]);
            Assert.AreEqual("Hidden Product", table.Rows[4].Values[2], "Hidden rows must preserve current behavior.");
            Assert.AreEqual("hidden-flag", table.Rows[4].Values[10], "Hidden columns must preserve current behavior.");

            var existing = new ProductDetailsRow
            {
                Barcode = "123456789012",
                ArticleCode = "OLD-EXISTING",
                Name = "Existing Before",
                Name2 = "Existing Before 2",
                PurchasePrice = 100,
                UnitPrice = 200,
                StockQty = 1,
                SupplierName = "Old Supplier",
                CategoryName = "Old Category"
            };
            var analysis = SupplierImportAnalyzer.Analyze(table, new[] { existing });
            Assert.AreEqual(0, analysis.Errors.Count);
            Assert.AreEqual(4, analysis.EditableRows.Count);
            CollectionAssert.AreEqual(new[] { 4, 5, 7, 9 }, analysis.EditableRows.Select(row => row.RowNumber).ToArray());
            var duplicate = analysis.Warnings.Single(warning =>
                warning.Message.Contains("duplicato", StringComparison.OrdinalIgnoreCase));
            CollectionAssert.AreEqual(new[] { 6, 7 }, duplicate.Rows.ToArray());
            Assert.AreEqual("Duplicate Last", analysis.EditableRows.Single(row => row.RowNumber == 7).ProductName);
            Assert.AreEqual(3, analysis.NewProducts.Count);
            Assert.AreEqual(1, analysis.UpdatedProducts.Count);

            var preview = SupplierImportAnalyzer.BuildSyncPreview(analysis.EditableRows, new[] { existing });
            Assert.IsTrue(preview.CanApply);
            Assert.AreEqual(3, preview.Summary.NewProducts);
            Assert.AreEqual(1, preview.Summary.UpdatedProducts);
            Assert.AreEqual(0, preview.Summary.NoChangeRows);
            Assert.AreEqual(0, preview.Summary.SkippedRows);

            var snapshot = BuildSnapshot(table, analysis, preview);
            Assert.AreEqual(
                "c65c648b67c415f36b4ba3015263b16a7316ef3c7c3cab5d17eb35276a22e813",
                Sha256(snapshot),
                "Current-reader semantic snapshot changed:" + Environment.NewLine + snapshot);
        }
        finally
        {
            TryDelete(path);
        }
    }

    [TestMethod]
    public void ReadFirstWorksheet_XlsxCanonicalAndHeaderless_KeepDetectionContract()
    {
        using var culture = new CultureScope(CultureInfo.InvariantCulture);
        var canonicalPath = TempPath(".xlsx");
        var headerlessPath = TempPath(".xlsx");
        try
        {
            using (var workbook = new XLWorkbook())
            {
                var sheet = workbook.Worksheets.Add("Canonical");
                var headers = new[]
                {
                    AndroidImportKeys.Barcode,
                    AndroidImportKeys.ProductName,
                    AndroidImportKeys.PurchasePrice,
                    AndroidImportKeys.RetailPrice
                };
                for (var column = 0; column < headers.Length; column++)
                    sheet.Cell(1, column + 1).Value = headers[column];
                sheet.Cell(2, 1).Value = "12345678";
                sheet.Cell(2, 2).Value = "Canonical Product";
                sheet.Cell(2, 3).Value = 100;
                sheet.Cell(2, 4).Value = 180;
                workbook.SaveAs(canonicalPath);
            }

            using (var workbook = new XLWorkbook())
            {
                var sheet = workbook.Worksheets.Add("Headerless");
                var rows = new[]
                {
                    new[] { "1234567890123", "Pattern One", "10", "1.000", "10.000", "AB12", "1.500", "Second One", "Supplier Pattern", "10%", "900", "1" },
                    new[] { "9876543210987", "Pattern Two", "5", "2.000", "10.000", "CD34", "2.500", "Second Two", "Supplier Pattern", "5%", "1900", "2" }
                };
                for (var row = 0; row < rows.Length; row++)
                    for (var column = 0; column < rows[row].Length; column++)
                        sheet.Cell(row + 1, column + 1).Value = rows[row][column];
                workbook.SaveAs(headerlessPath);
            }

            var canonical = SupplierExcelImportReader.ReadFirstWorksheet(canonicalPath);
            Assert.IsTrue(canonical.HasHeader);
            Assert.AreEqual(1, canonical.DataRowIndex);
            Assert.IsTrue(canonical.Columns.All(column => column.HeaderSource == "alias"));
            CollectionAssert.AreEqual(new[] { 2 }, canonical.Rows.Select(row => row.RowNumber).ToArray());

            var headerless = SupplierExcelImportReader.ReadFirstWorksheet(headerlessPath);
            Assert.IsFalse(headerless.HasHeader);
            Assert.AreEqual(0, headerless.DataRowIndex);
            CollectionAssert.AreEqual(new[] { 1, 2 }, headerless.Rows.Select(row => row.RowNumber).ToArray());
            AssertColumn(headerless, AndroidImportKeys.Barcode, "pattern");
            AssertColumn(headerless, AndroidImportKeys.ProductName, "pattern");
            AssertColumn(headerless, AndroidImportKeys.Quantity, "pattern");
            AssertColumn(headerless, AndroidImportKeys.PurchasePrice, "pattern");
            AssertColumn(headerless, AndroidImportKeys.TotalPrice, "pattern");
            AssertColumn(headerless, AndroidImportKeys.ItemNumber, "pattern");
            AssertColumn(headerless, AndroidImportKeys.RetailPrice, "pattern");
            AssertColumn(headerless, AndroidImportKeys.SecondProductName, "pattern");
            AssertColumn(headerless, AndroidImportKeys.Supplier, "pattern");
            AssertColumn(headerless, AndroidImportKeys.Discount, "pattern");
            AssertColumn(headerless, AndroidImportKeys.DiscountedPrice, "pattern");
            AssertColumn(headerless, AndroidImportKeys.RowNumber, "pattern");
        }
        finally
        {
            TryDelete(canonicalPath);
            TryDelete(headerlessPath);
        }
    }

    [TestMethod]
    public void ReadFirstWorksheet_XlsxMergedCells_PreservesCurrentTopLeftBehavior()
    {
        using var culture = new CultureScope(CultureInfo.InvariantCulture);
        var path = TempPath(".xlsx");
        try
        {
            using (var workbook = new XLWorkbook())
            {
                var sheet = workbook.Worksheets.Add("Merged");
                sheet.Cell(1, 1).Value = AndroidImportKeys.Barcode;
                sheet.Cell(1, 2).Value = AndroidImportKeys.ProductName;
                sheet.Cell(1, 3).Value = AndroidImportKeys.PurchasePrice;
                sheet.Cell(1, 4).Value = AndroidImportKeys.RetailPrice;
                sheet.Cell(1, 5).Value = "Notes";
                sheet.Range(1, 5, 1, 6).Merge();
                sheet.Cell(2, 1).Value = "87654321";
                sheet.Cell(2, 2).Value = "Merged Product";
                sheet.Cell(2, 3).Value = 100;
                sheet.Cell(2, 4).Value = 180;
                sheet.Range(2, 5, 2, 6).Merge();
                sheet.Cell(2, 5).Value = "Merged Value";
                workbook.SaveAs(path);
            }

            var table = SupplierExcelImportReader.ReadFirstWorksheet(path);

            Assert.AreEqual(5, table.Columns.Count);
            Assert.AreEqual("Notes", table.Columns[4].OriginalHeader);
            Assert.AreEqual("Merged Value", table.Rows.Single().Values[4]);
        }
        finally
        {
            TryDelete(path);
        }
    }

    [TestMethod]
    public void ReadFirstWorksheet_XlsxFormula_PreservesClosedXmlCompatibilityResult()
    {
        using var culture = new CultureScope(CultureInfo.InvariantCulture);
        var path = TempPath(".xlsx");
        try
        {
            using (var workbook = new XLWorkbook())
            {
                var sheet = workbook.Worksheets.Add("Formula");
                sheet.Cell(1, 1).Value = AndroidImportKeys.Barcode;
                sheet.Cell(1, 2).Value = AndroidImportKeys.ProductName;
                sheet.Cell(1, 3).Value = AndroidImportKeys.PurchasePrice;
                sheet.Cell(1, 4).Value = AndroidImportKeys.RetailPrice;
                sheet.Cell(1, 5).Value = AndroidImportKeys.TotalPrice;
                sheet.Cell(2, 1).Value = "12345678";
                sheet.Cell(2, 2).Value = "Formula Product";
                sheet.Cell(2, 3).Value = 1234.56;
                sheet.Cell(2, 4).Value = 1990;
                sheet.Cell(2, 5).FormulaA1 = "C2*2";
                sheet.Cell(2, 5).Style.NumberFormat.Format = "0.00";
                workbook.RecalculateAllFormulas();
                workbook.SaveAs(path);
            }

            var table = SupplierExcelImportReader.ReadFirstWorksheet(path);
            Assert.AreEqual(1, table.Rows.Count);
            Assert.AreEqual("2469.12", table.Rows[0].Values[4]);
        }
        finally
        {
            TryDelete(path);
        }
    }

    [TestMethod]
    public void ReadFirstWorksheet_HtmlXls_PreservesRowspanColspanAndEntities()
    {
        var path = TempPath(".xls");
        try
        {
            File.WriteAllText(
                path,
                "<html><head><meta charset=\"utf-8\"><meta name=\"ProgId\" content=\"Excel.Sheet\"></head><body>" +
                "<table><tr><td>ignore</td></tr></table>" +
                "<table>" +
                "<tr><th>barcode</th><th>productName</th><th>purchasePrice</th><th>retailPrice</th><th>quantity</th></tr>" +
                "<tr><td rowspan=\"2\">00123456</td><td colspan=\"2\">Alpha &amp; Beta</td><td>200</td><td>2</td></tr>" +
                "<tr><td>Second<br/>Name</td><td>100</td><td>210</td><td>3</td></tr>" +
                "</table></body></html>",
                Encoding.UTF8);

            Assert.AreEqual(1, SupplierExcelImportReader.CountWorksheets(path));
            var table = SupplierExcelImportReader.ReadFirstWorksheet(path);

            Assert.AreEqual(2, table.Rows.Count);
            CollectionAssert.AreEqual(
                new[] { "00123456", "Alpha & Beta", "Alpha & Beta", "200", "2" },
                table.Rows[0].Values.ToArray());
            CollectionAssert.AreEqual(
                new[] { "00123456", "Second Name", "100", "210", "3" },
                table.Rows[1].Values.ToArray());
            var analysis = SupplierImportAnalyzer.Analyze(table, Array.Empty<ProductDetailsRow>());
            Assert.AreEqual(1, analysis.EditableRows.Count);
            Assert.AreEqual("Second Name", analysis.EditableRows[0].ProductName);
            CollectionAssert.AreEqual(
                new[] { 2, 3 },
                analysis.Warnings.Single(warning =>
                    warning.Message.Contains("duplicato", StringComparison.OrdinalIgnoreCase)).Rows.ToArray());
        }
        finally
        {
            TryDelete(path);
        }
    }

    [TestMethod]
    public void ReadFirstWorksheet_RealBinaryXls_RemainsSupported()
    {
        var path = TempPath(".xls");
        try
        {
            File.WriteAllBytes(path, Convert.FromBase64String(RealBinaryXlsBase64));

            Assert.IsTrue(SupplierExcelImportReader.IsSupportedWorkbookFile(path));
            Assert.AreEqual(1, SupplierExcelImportReader.CountWorksheets(path));
            var table = SupplierExcelImportReader.ReadFirstWorksheet(path);

            Assert.AreEqual("Sheet1", table.SheetName);
            Assert.AreEqual(10, table.Rows.Count);
            Assert.AreEqual("col1", table.Rows[0].Values[0]);
            Assert.AreEqual("10x10", table.Rows[1].Values[0]);
            Assert.AreEqual("10x27", table.Rows[9].Values[9]);
        }
        finally
        {
            TryDelete(path);
        }
    }

    [TestMethod]
    public void ReadFirstWorksheet_ClosedXmlIncompatibleXlsx_UsesExcelDataReaderPath()
    {
        var path = TempPath(".xlsx");
        try
        {
            File.WriteAllBytes(path, Convert.FromBase64String(ClosedXmlFallbackXlsxBase64));

            Exception? closedXmlFailure = null;
            try
            {
                using var workbook = new XLWorkbook(path);
            }
            catch (Exception ex)
            {
                closedXmlFailure = ex;
            }

            Assert.IsNotNull(closedXmlFailure, "Fixture no longer proves ExcelDataReader compatibility beyond ClosedXML.");
            var table = SupplierExcelImportReader.ReadFirstWorksheet(path);

            Assert.AreEqual("Sheet1", table.SheetName);
            Assert.AreEqual(10, table.Rows.Count);
            Assert.AreEqual("col1", table.Rows[0].Values[0]);
            Assert.AreEqual("10x10", table.Rows[1].Values[0]);
            Assert.AreEqual("10x27", table.Rows[9].Values[9]);
        }
        finally
        {
            TryDelete(path);
        }
    }

    [TestMethod]
    public void ReadFirstWorksheet_FirstSheetContractAndFileSharing_AreStable()
    {
        var path = TempPath(".xlsx");
        var movedPath = path + ".moved.xlsx";
        try
        {
            using (var workbook = new XLWorkbook())
            {
                var first = workbook.Worksheets.Add("First Contract");
                first.Cell(1, 1).Value = AndroidImportKeys.Barcode;
                first.Cell(1, 2).Value = AndroidImportKeys.ProductName;
                first.Cell(1, 3).Value = AndroidImportKeys.PurchasePrice;
                first.Cell(1, 4).Value = AndroidImportKeys.RetailPrice;
                first.Cell(2, 1).Value = "12345678";
                first.Cell(2, 2).Value = "First Product";
                first.Cell(2, 3).Value = 100;
                first.Cell(2, 4).Value = 180;

                var second = workbook.Worksheets.Add("Second Must Be Ignored");
                for (var row = 1; row <= 250; row++)
                {
                    second.Cell(row, 1).Value = "SECOND-" + row.ToString(CultureInfo.InvariantCulture);
                    second.Cell(row, 2).Value = new string('x', 128);
                }

                workbook.SaveAs(path);
            }

            using (var shared = new FileStream(
                path,
                FileMode.Open,
                FileAccess.Read,
                FileShare.ReadWrite | FileShare.Delete))
            {
                Assert.AreEqual(2, SupplierExcelImportReader.CountWorksheets(path));
                var table = SupplierExcelImportReader.ReadFirstWorksheet(path);
                Assert.AreEqual("First Contract", table.SheetName);
                Assert.AreEqual(1, table.Rows.Count);
                Assert.AreEqual("First Product", table.Rows[0].Values[1]);
            }

            File.Move(path, movedPath);
            File.Delete(movedPath);
            Assert.IsFalse(File.Exists(movedPath), "Reader or counter retained a file handle.");
        }
        finally
        {
            TryDelete(path);
            TryDelete(movedPath);
        }
    }

    [TestMethod]
    public void ReadFirstWorksheet_UnsupportedAndCorruptInputs_ReturnStableRecoverableCode()
    {
        var unsupportedPath = TempPath(".txt");
        var corruptPath = TempPath(".xlsx");
        try
        {
            File.WriteAllText(unsupportedPath, "not an excel workbook", Encoding.UTF8);
            File.WriteAllText(corruptPath, "not an xlsx zip", Encoding.UTF8);

            var unsupported = CaptureException(() => SupplierExcelImportReader.ReadFirstWorksheet(unsupportedPath));
            Assert.IsInstanceOfType<SupplierExcelImportException>(unsupported);
            Assert.AreEqual(
                SupplierExcelImportErrorCodes.CorruptOrUnsupported,
                ((SupplierExcelImportException)unsupported).Code);

            var corrupt = CaptureException(() => SupplierExcelImportReader.ReadFirstWorksheet(corruptPath));
            Assert.IsInstanceOfType<SupplierExcelImportException>(corrupt);
            Assert.AreEqual(
                SupplierExcelImportErrorCodes.CorruptOrUnsupported,
                ((SupplierExcelImportException)corrupt).Code);
            Assert.AreEqual(unsupported.Message, corrupt.Message);
        }
        finally
        {
            TryDelete(unsupportedPath);
            TryDelete(corruptPath);
        }
    }

    private static void WriteSemanticWorkbook(string path)
    {
        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add("Semantic First");
        sheet.Cell(1, 1).Value = "Supplier export";
        sheet.Cell(2, 1).Value = "Generated 2026-08-02";
        var headers = new[]
        {
            "Codice a barre",
            "Codice articolo",
            "Nome prodotto",
            "Secondo nome prodotto",
            "Prezzo acquisto",
            "Prezzo vendita",
            "Stock",
            "Fornitore",
            "Categoria",
            "Totale",
            "Flag",
            "Data"
        };
        for (var column = 0; column < headers.Length; column++)
            sheet.Cell(3, column + 1).Value = headers[column];

        sheet.Cell(4, 1).Value = 123456;
        sheet.Cell(4, 1).Style.NumberFormat.Format = "00000000";
        WriteSemanticRowTail(sheet, 4, "A-001", "Alpha", "Alpha Second", 1234.56, 1990, 2, "Supplier A", "Category A");
        sheet.Cell(4, 10).Value = 2469.12;
        sheet.Cell(4, 10).Style.NumberFormat.Format = "0.00";
        sheet.Cell(4, 11).Value = true;
        sheet.Cell(4, 12).Value = new DateTime(2026, 8, 2);
        sheet.Cell(4, 12).Style.DateFormat.Format = "yyyy-MM-dd";

        sheet.Cell(5, 1).Value = "123456789012";
        WriteSemanticRowTail(sheet, 5, "B-002", "Existing Updated", "Existing Updated 2", "1.234,56", "1,234.56", "3", "Supplier B", "Category B");
        sheet.Cell(5, 10).Value = "1234,56";
        sheet.Cell(5, 11).Value = false;
        sheet.Cell(5, 12).Value = new DateTime(2026, 8, 3);
        sheet.Cell(5, 12).Style.DateFormat.Format = "yyyy-MM-dd";

        sheet.Cell(6, 1).Value = "1234567890123";
        WriteSemanticRowTail(sheet, 6, "C-OLD", "Duplicate First", "Duplicate First 2", 100, 180, 1, "Supplier C", "Category C");
        sheet.Cell(6, 10).Value = 100;

        sheet.Cell(7, 1).Value = "1234567890123";
        WriteSemanticRowTail(sheet, 7, "C-LAST", "Duplicate Last", "Duplicate Last 2", 120, 190, 2, "Supplier C", "Category C");
        sheet.Cell(7, 10).Value = 240;

        sheet.Cell(8, 3).Value = "Totale";
        sheet.Cell(8, 5).Value = 2554.56;
        sheet.Cell(8, 6).Value = 3660;
        sheet.Cell(8, 7).Value = 8;
        sheet.Cell(8, 10).Value = 5109.12;

        sheet.Cell(9, 1).Value = "87654321";
        WriteSemanticRowTail(sheet, 9, "H-009", "Hidden Product", "Hidden Second", 50, 90, 1, "Hidden Supplier", "Hidden Category");
        sheet.Cell(9, 10).Value = 50;
        sheet.Cell(9, 11).Value = "hidden-flag";
        sheet.Cell(9, 12).Value = new DateTime(2026, 8, 4);
        sheet.Cell(9, 12).Style.DateFormat.Format = "yyyy-MM-dd";
        sheet.Row(9).Hide();
        sheet.Column(11).Hide();

        sheet.Cell(10, 12).Value = "   ";

        var ignored = workbook.Worksheets.Add("Ignored Second");
        ignored.Cell(1, 1).Value = "This worksheet must never be imported";
        for (var row = 2; row <= 200; row++)
            ignored.Cell(row, 1).Value = "ignored-" + row.ToString(CultureInfo.InvariantCulture);

        workbook.RecalculateAllFormulas();
        workbook.SaveAs(path);
    }

    private static void WriteSemanticRowTail(
        IXLWorksheet sheet,
        int row,
        object item,
        object productName,
        object secondName,
        object purchase,
        object retail,
        object quantity,
        object supplier,
        object category)
    {
        sheet.Cell(row, 2).Value = XLCellValue.FromObject(item);
        sheet.Cell(row, 3).Value = XLCellValue.FromObject(productName);
        sheet.Cell(row, 4).Value = XLCellValue.FromObject(secondName);
        sheet.Cell(row, 5).Value = XLCellValue.FromObject(purchase);
        sheet.Cell(row, 6).Value = XLCellValue.FromObject(retail);
        sheet.Cell(row, 7).Value = XLCellValue.FromObject(quantity);
        sheet.Cell(row, 8).Value = XLCellValue.FromObject(supplier);
        sheet.Cell(row, 9).Value = XLCellValue.FromObject(category);
    }

    private static string BuildSnapshot(
        SupplierExcelRawTable table,
        SupplierImportAnalysis analysis,
        SupplierImportSyncPreview preview)
    {
        var builder = new StringBuilder();
        builder.AppendLine($"table|{Escape(table.SheetName)}|{table.HasHeader}|{table.DataRowIndex}|{table.DroppedSummaryRows}");
        foreach (var column in table.Columns)
        {
            builder.AppendLine(
                $"column|{column.ColumnIndex}|{Escape(column.OriginalHeader)}|{Escape(column.DisplayName)}|" +
                $"{Escape(column.CanonicalKey)}|{Escape(column.HeaderSource)}|{Escape(column.Confidence)}|" +
                $"{column.IsEnabled}|{column.IsGenerated}|{Escape(column.SampleValues)}");
        }
        foreach (var row in table.Rows)
            builder.AppendLine($"row|{row.RowNumber}|{string.Join("|", row.Values.Select(Escape))}");
        builder.AppendLine(
            $"analysis|{analysis.HasHeader}|{analysis.DataRowIndex}|{analysis.HeaderRowNumber}|" +
            $"{analysis.SkippedMetadataRows}|{analysis.DroppedSummaryRows}|{analysis.SourceRowCount}|" +
            $"{analysis.EditableRows.Count}|{analysis.NewProducts.Count}|{analysis.UpdatedProducts.Count}");
        foreach (var warning in analysis.Warnings)
            builder.AppendLine($"warning|{Escape(warning.Message)}|{string.Join(",", warning.Rows)}");
        foreach (var error in analysis.Errors)
            builder.AppendLine($"error|{error.RowIndex}|{Escape(error.Barcode)}|{Escape(error.Message)}");
        foreach (var row in analysis.EditableRows)
        {
            builder.AppendLine(
                $"editable|{row.RowNumber}|{Escape(row.Barcode)}|{Escape(row.ItemNumber)}|" +
                $"{Escape(row.ProductName)}|{Escape(row.SecondProductName)}|{Escape(row.PurchasePrice)}|" +
                $"{Escape(row.RetailPrice)}|{Escape(row.Quantity)}|{Escape(row.Supplier)}|" +
                $"{Escape(row.Category)}|{row.Exists}|{row.IsSkipped}");
        }
        builder.AppendLine(
            $"preview|{preview.Summary.TotalRows}|{preview.Summary.NonSkippedRows}|" +
            $"{preview.Summary.NewProducts}|{preview.Summary.UpdatedProducts}|" +
            $"{preview.Summary.NoChangeRows}|{preview.Summary.SkippedRows}|" +
            $"{preview.Summary.WarningCount}|{preview.Summary.ErrorCount}|{preview.CanApply}|" +
            $"{preview.Fingerprint}");
        return builder.ToString();
    }

    private static string Escape(string value)
    {
        return (value ?? string.Empty)
            .Replace("\\", "\\\\")
            .Replace("|", "\\|")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n");
    }

    private static string Sha256(string value)
    {
        using var sha = SHA256.Create();
        return Convert.ToHexString(sha.ComputeHash(Encoding.UTF8.GetBytes(value ?? string.Empty))).ToLowerInvariant();
    }

    private static void AssertColumn(SupplierExcelRawTable table, string key, string source)
    {
        Assert.IsTrue(
            table.Columns.Any(column =>
                string.Equals(column.CanonicalKey, key, StringComparison.Ordinal) &&
                string.Equals(column.HeaderSource, source, StringComparison.Ordinal)),
            $"Expected {key} from {source}.");
    }

    private static Exception CaptureException(Action action)
    {
        try
        {
            action();
        }
        catch (Exception ex)
        {
            return ex;
        }

        Assert.Fail("Expected operation to fail.");
        return new InvalidOperationException("Unreachable");
    }

    private static string TempPath(string extension)
    {
        return Path.Combine(
            Path.GetTempPath(),
            "win7pos-supplier-reader-" + Guid.NewGuid().ToString("N") + extension);
    }

    private static void TryDelete(string path)
    {
        try
        {
            if (File.Exists(path))
                File.Delete(path);
        }
        catch
        {
        }
    }

    private sealed class CultureScope : IDisposable
    {
        private readonly CultureInfo _culture;
        private readonly CultureInfo _uiCulture;

        public CultureScope(CultureInfo culture)
        {
            _culture = CultureInfo.CurrentCulture;
            _uiCulture = CultureInfo.CurrentUICulture;
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;
        }

        public void Dispose()
        {
            CultureInfo.CurrentCulture = _culture;
            CultureInfo.CurrentUICulture = _uiCulture;
        }
    }
}
