using System.Collections.Generic;

namespace Win7POS.Wpf.Localization
{
    public sealed partial class PosLocalization
    {
        private static void AddImportRecoveryTranslations(Dictionary<string, Dictionary<string, string>> catalog)
        {
            RecoveryText(catalog, "recoveryCapacity", "Admin has insufficient capacity to save this recovery plan. Your draft is retained. Ask support to review recovery capacity, then retry verification.", "Admin no tiene capacidad suficiente para guardar este plan de recuperación. Se conserva el borrador. Solicita soporte para revisar la capacidad y vuelve a verificar.", "Admin non ha capacità sufficiente per salvare questo piano di recupero. La bozza è conservata. Richiedi assistenza per verificare la capacità, poi riprova la verifica.", "Admin 空间不足，无法保存此恢复计划。草稿已保留。请联系支持人员检查恢复容量，然后重新验证。");
            RecoveryText(catalog, "preparedPlan", "Recovery plan saved before sending. Changes have not been applied locally. Verify to resume the same saved operations.", "Plan de recuperación guardado antes del envío. Los cambios no se han aplicado localmente. Verifica para reanudar las mismas operaciones guardadas.", "Piano di recupero salvato prima dell’invio. Le modifiche non sono state applicate localmente. Verifica per riprendere le stesse operazioni salvate.", "恢复计划已在发送前保存，修改尚未在本地应用。请验证后继续执行相同的已保存操作。");
            RecoveryText(catalog, "preparedPlanConflict", "The saved recovery plan requires review because its values or catalog revisions differ. Keep the saved operations and verify their outcome before changing the plan.", "Hay que revisar el plan guardado porque cambiaron los valores o revisiones del catálogo. Conserva las operaciones y verifica su resultado antes de cambiar el plan.", "Il piano salvato richiede una revisione perché valori o revisioni del catalogo sono diversi. Conserva le operazioni e verificane l’esito prima di cambiare il piano.", "数值或商品目录版本发生变化，需要检查已保存的恢复计划。请保留操作并核实结果后再修改计划。");
            RecoveryText(catalog, "retirePreparedPlan", "Retire pending parts", "Retirar partes pendientes", "Ritira parti in sospeso", "停用待处理分批");
            RecoveryText(catalog, "retirePreparedPlanConfirm", "Admin will verify every saved part and retire those still pending, so delayed requests cannot apply them. Accepted parts and their receipts will be preserved. You will then review the remaining work before applying a new plan. Continue?", "Admin verificará cada parte guardada y retirará las pendientes para impedir que solicitudes retrasadas las apliquen. Se conservarán las partes aceptadas y sus recibos. Después revisarás el trabajo restante antes de aplicar un nuevo plan. ¿Continuar?", "Admin verificherà ogni parte salvata e ritirerà quelle ancora in sospeso, impedendone l’applicazione tramite richieste ritardate. Le parti accettate e le relative ricevute saranno conservate. Potrai poi rivedere il lavoro restante prima di applicare un nuovo piano. Continuare?", "Admin 将核实每个已保存的分批并停用仍待处理的分批，防止延迟请求应用它们。已接受的分批及其回执将保留。之后可检查剩余工作，再应用新计划。是否继续？");
            RecoveryText(catalog, "deferredDraftSaved", "Changes to already accepted rows remain saved as an unapplied draft. After this group finishes, reopen recovery to review and apply them separately.", "Los cambios en filas ya aceptadas siguen guardados como borrador sin aplicar. Al terminar este grupo, vuelve a abrir la recuperación para revisarlos y aplicarlos por separado.", "Le modifiche alle righe già accettate restano salvate come bozza non applicata. Quando il gruppo sarà concluso, riapri il recupero per rivederle e applicarle separatamente.", "对已接受行的修改已保留为尚未应用的草稿。此组完成后，请重新打开恢复功能，单独检查并应用这些修改。");
            RecoveryText(catalog, "fieldTooLong", "{0}: maximum {1} characters. Shorten this value before saving. No changes were applied.", "{0}: máximo {1} caracteres. Acorta este valor antes de guardar. No se aplicaron cambios.", "{0}: massimo {1} caratteri. Riduci questo valore prima di salvare. Nessuna modifica applicata.", "{0}：最多 {1} 个字符。保存前请缩短此值。未应用任何更改。");
            RecoveryText(catalog, "fieldInvalidUnicode", "{0} contains a character Admin cannot store. Correct this value before saving. No changes were applied.", "{0} contiene un carácter que Admin no puede guardar. Corrige este valor antes de guardar. No se aplicaron cambios.", "{0} contiene un carattere che Admin non può memorizzare. Correggi il valore prima di salvare. Nessuna modifica applicata.", "{0} 包含 Admin 无法存储的字符。保存前请修改此值。未应用任何更改。");
            RecoveryText(catalog, "draftExplanation", "Edits are saved as a draft. Verify them before applying.", "Los cambios se guardan como borrador. Verifícalos antes de aplicar.", "Le modifiche vengono salvate come bozza. Verificale prima di applicare.", "修改将保存为草稿，请在应用前验证。");
            RecoveryText(catalog, "draftSaving", "Saving draft…", "Guardando borrador…", "Salvataggio bozza…", "正在保存草稿…");
            RecoveryText(catalog, "draftSaved", "Draft saved on this till. Prices and stock have not been changed by saving the draft.", "Borrador guardado en esta caja. Guardar el borrador no modifica precios ni stock.", "Bozza salvata su questa cassa. Il salvataggio della bozza non modifica prezzi e stock.", "草稿已保存在此收银机。保存草稿不会修改价格或库存。");
            RecoveryText(catalog, "draftStale", "Draft restored; the shop session or catalog has changed. Review the values and verify again before applying.", "Borrador recuperado; cambió la sesión o el catálogo. Revisa los valores y vuelve a verificar antes de aplicar.", "Bozza recuperata; la sessione o il catalogo sono cambiati. Rivedi i valori e verifica di nuovo prima di applicare.", "已恢复草稿，但会话或商品目录已更改。请检查数值并重新验证后再应用。");
            RecoveryText(catalog, "draftSaveFailed", "The draft could not be saved. Keep this window open and retry closing, or explicitly discard the draft.", "No se pudo guardar el borrador. Mantén abierta esta ventana y reintenta cerrarla, o descarta el borrador.", "Impossibile salvare la bozza. Mantieni aperta la finestra e riprova a chiudere, oppure scarta esplicitamente la bozza.", "无法保存草稿。请保持此窗口打开并重试关闭，或明确放弃草稿。");
            RecoveryText(catalog, "discardDraft", "Discard draft", "Descartar borrador", "Scarta bozza", "放弃草稿");
            RecoveryText(catalog, "discardDraftConfirm", "Discard unapplied edits? Saved import operations will remain in the queue.", "¿Descartar los cambios sin aplicar? Las operaciones de importación guardadas seguirán en la cola.", "Scartare le modifiche non applicate? Le operazioni di importazione salvate resteranno in coda.", "放弃尚未应用的修改？已保存的导入操作仍会保留在队列中。");
            RecoveryText(catalog, "localSaved", "Changes saved locally. Remote confirmation is shown separately below.", "Cambios guardados localmente. La confirmación remota se muestra abajo.", "Modifiche salvate localmente. La conferma remota è mostrata separatamente sotto.", "修改已在本地保存，远程确认进度显示在下方。");
            RecoveryText(catalog, "planProgress", "Admin confirmed {0}/{1} rows · {2}/{3} parts.", "Admin confirmó {0}/{1} filas · {2}/{3} partes.", "Admin ha confermato {0}/{1} righe · {2}/{3} parti.", "Admin 已确认 {0}/{1} 行 · {2}/{3} 个部分。");
            RecoveryText(catalog, "planFailed", "{0} part(s) need attention; confirmed parts are retained.", "{0} parte(s) requieren atención; las confirmadas se conservan.", "{0} parti richiedono attenzione; le parti confermate restano acquisite.", "{0} 个部分需要处理，已确认的部分会保留。");
            RecoveryText(catalog, "progressUnavailable", "Progress is temporarily unavailable. Saved operations remain in the queue.", "El progreso no está disponible temporalmente. Las operaciones guardadas siguen en la cola.", "Avanzamento temporaneamente non disponibile. Le operazioni salvate restano in coda.", "暂时无法读取进度，已保存的操作仍保留在队列中。");
            RecoveryText(catalog, "partsQueued", "{0} parts saved for automatic synchronization. Check remote confirmations in Sync Center.", "{0} partes guardadas para sincronización automática. Consulta las confirmaciones remotas en el Centro de sincronización.", "{0} parti salvate per la sincronizzazione automatica. Verifica le conferme remote nel Centro sincronizzazione.", "已保存 {0} 个部分，等待自动同步。请在同步中心查看远程确认。");
            RecoveryText(catalog, "title", "Recover blocked import", "Recuperar importación bloqueada", "Recupera importazione bloccata", "恢复已阻止的导入");
            RecoveryText(catalog, "open", "Review and recover", "Revisar y recuperar", "Verifica e recupera", "检查并恢复");
            RecoveryText(catalog, "explanation", "Review the original rows. Correct prices using whole CLP amounts from 0 to 999,999,999, then verify. The original batch stays blocked until Admin confirms the replacement.", "Revisa las filas originales. Corrige los precios con importes enteros en CLP de 0 a 999.999.999 y verifica. El lote original permanece bloqueado hasta que Admin confirme el reemplazo.", "Verifica le righe originali. Correggi i prezzi con importi interi CLP da 0 a 999.999.999, poi verifica. Il batch originale resta bloccato finché Admin conferma la sostituzione.", "检查原始行。将价格修改为 0 到 999,999,999 之间的整数 CLP 金额，然后验证。在 Admin 确认替代批次之前，原批次将保持阻止状态。");
            RecoveryText(catalog, "batch", "Blocked import #{0} · {1} rows", "Importación bloqueada #{0} · {1} filas", "Importazione bloccata #{0} · {1} righe", "已阻止的导入 #{0} · {1} 行");
            RecoveryText(catalog, "rows", "Original import rows", "Filas originales", "Righe originali", "原始导入行");
            RecoveryText(catalog, "barcode", "Barcode", "Código de barras", "Codice a barre", "条码");
            RecoveryText(catalog, "product", "Product", "Producto", "Prodotto", "商品");
            RecoveryText(catalog, "purchase", "Purchase price", "Precio de compra", "Prezzo acquisto", "进价");
            RecoveryText(catalog, "retail", "Retail price", "Precio de venta", "Prezzo vendita", "售价");
            RecoveryText(catalog, "quantity", "Quantity", "Cantidad", "Quantità", "数量");
            RecoveryText(catalog, "quantityExplanation", "Quantity refers to the original import. Its correction adjusts current local stock by the difference, preserving later local movements.", "La cantidad corresponde a la importación original. Su corrección ajusta el stock local actual por la diferencia y conserva los movimientos locales posteriores.", "La quantità si riferisce all’importazione originale. La correzione applica la differenza allo stock locale corrente, conservando i movimenti locali successivi.", "数量指原始导入数量。修改时将差额应用于当前本地库存，并保留后续本地库存变动。");
            RecoveryText(catalog, "data", "Import data", "Datos de importación", "Dati importazione", "导入数据");
            RecoveryText(catalog, "verify", "Verify corrections", "Verificar correcciones", "Verifica correzioni", "验证修改");
            RecoveryText(catalog, "retire", "Retire pending identity", "Retirar identidad pendiente", "Ritira identità in sospeso", "停用待处理标识");
            RecoveryText(catalog, "retireConfirm", "Admin found no accepted receipt for the pending request. Retire its identity so a delayed request cannot apply it later? No products are changed by retirement. You can then queue a corrected replacement.", "Admin no encontró un recibo aceptado para la solicitud pendiente. ¿Retirar su identidad para impedir que una solicitud retrasada la aplique después? No se modifican productos. Luego podrás enviar un reemplazo corregido.", "Admin non ha trovato una ricevuta accettata per la richiesta in sospeso. Ritirarne l’identità per impedire a una richiesta ritardata di applicarla in seguito? Il ritiro non modifica prodotti. Potrai poi accodare una sostituzione corretta.", "Admin 未找到待处理请求的已接受回执。是否停用其标识以防止延迟请求日后应用？停用不会修改商品。之后可以排队发送修改后的替代批次。");
            RecoveryText(catalog, "commit", "Save and queue replacement", "Guardar y enviar reemplazo", "Salva e accoda sostituzione", "保存并排队替代批次");
            RecoveryText(catalog, "reconcileAccepted", "Confirm accepted receipt", "Confirmar recibo aceptado", "Conferma ricevuta accettata", "确认已接受回执");
            RecoveryText(catalog, "acceptedPendingReconciliation", "Admin already accepted the previous replacement. Confirm its receipt to complete local reconciliation.", "Admin ya aceptó el reemplazo anterior. Confirma su recibo para completar la conciliación local.", "Admin ha già accettato la sostituzione precedente. Conferma la ricevuta per completare la riconciliazione locale.", "Admin 已接受上一次替代批次。请确认其回执以完成本地核对。");
            RecoveryText(catalog, "acceptedDraftRetained", "Draft values are saved. This confirmation reconciles the accepted operation. Reopen recovery afterwards to review and apply the remaining draft changes.", "Los valores del borrador están guardados. Esta confirmación concilia la operación aceptada. Después, vuelve a abrir la recuperación para revisar y aplicar los cambios pendientes del borrador.", "I valori della bozza sono salvati. Questa conferma riconcilia l’operazione accettata. Poi riapri il recupero per rivedere e applicare le modifiche ancora presenti nella bozza.", "草稿值已保存。本次确认用于核对已接受的操作。随后重新打开恢复，检查并应用草稿中剩余的更改。");
            RecoveryText(catalog, "acceptedReconciled", "The previously accepted replacement has been reconciled. The draft remains saved; reopen recovery to review and apply its remaining changes.", "Se concilió el reemplazo aceptado anteriormente. El borrador sigue guardado; vuelve a abrir la recuperación para revisar y aplicar sus cambios pendientes.", "La sostituzione già accettata è stata riconciliata. La bozza resta salvata; riapri il recupero per rivedere e applicare le modifiche ancora da eseguire.", "先前已接受的替代批次已核对完成。草稿仍已保存；请重新打开恢复，检查并应用剩余修改。");
            RecoveryText(catalog, "replacementBlocked", "The previous replacement needs review before recovery can continue.", "Hay que revisar el reemplazo anterior antes de continuar la recuperación.", "La sostituzione precedente richiede una verifica prima di continuare il recupero.", "继续恢复前，需要检查上一次替代批次。");
            RecoveryText(catalog, "batchLimit", "A row cannot fit within the Admin request limit, including verification data. Nothing was applied. The original and draft remain saved; review the reported row before retrying.", "Una fila no cabe en el límite de la solicitud a Admin, incluidos los datos de verificación. No se aplicó ningún cambio. El original y el borrador siguen guardados; revisa la fila indicada antes de reintentar.", "Una riga supera il limite della richiesta Admin, inclusi i dati di verifica. Nessuna modifica applicata. Originale e bozza restano salvati; rivedi la riga indicata prima di riprovare.", "某一行及其验证数据无法装入 Admin 请求限制。未应用任何更改。原始操作和草稿仍已保存；重试前请检查提示的行。");
            RecoveryText(catalog, "verifying", "Checking the batch and authoritative receipt…", "Comprobando el lote y el recibo autoritativo…", "Verifica del batch e della ricevuta autorevole…", "正在检查批次及权威回执…");
            RecoveryText(catalog, "editThenVerify", "Correct the fields, then select Verify corrections. Your draft is retained if verification fails.", "Corrige los campos y selecciona Verificar correcciones. El borrador se conserva si la verificación falla.", "Correggi i campi, poi seleziona Verifica correzioni. La bozza resta disponibile se la verifica fallisce.", "修改字段后选择“验证修改”。验证失败时将保留草稿。");
            RecoveryText(catalog, "previewReady", "Verified {0} original rows. Ready to save a new replacement batch.", "Verificadas {0} filas originales. Listo para guardar un nuevo lote de reemplazo.", "Verificate {0} righe originali. Puoi salvare un nuovo batch di sostituzione.", "已验证 {0} 个原始行。可以保存新的替代批次。");
            RecoveryText(catalog, "saving", "Creating a verified backup and saving the replacement…", "Creando una copia verificada y guardando el reemplazo…", "Creazione del backup verificato e salvataggio sostituzione…", "正在创建已验证的备份并保存替代批次…");
            RecoveryText(catalog, "cancelling", "Cancelling; waiting for the current operation to finish safely…", "Cancelando; esperando que la operación termine de forma segura…", "Annullamento: attesa della conclusione sicura dell’operazione…", "正在取消；等待当前操作安全结束…");
            RecoveryText(catalog, "queued", "Replacement saved locally and queued. Admin confirmation is still pending.", "Reemplazo guardado localmente y en cola. La confirmación de Admin sigue pendiente.", "Sostituzione salvata in locale e accodata. La conferma Admin è ancora in attesa.", "替代批次已在本地保存并排队，仍在等待 Admin 确认。");
            RecoveryText(catalog, "converged", "Admin receipts confirm all intended rows. Recovery is complete; no additional import was sent.", "Los recibos de Admin confirman todas las filas previstas. Recuperación completa; no se envió otra importación.", "Le ricevute Admin confermano tutte le righe previste. Recupero completato: nessun ulteriore import inviato.", "Admin 回执已确认所有预期行。恢复完成，未发送额外导入。");
            RecoveryText(catalog, "resolved", "Original batch resolved with authoritative receipts.", "Lote original resuelto con recibos autoritativos.", "Batch originale risolto con ricevute autorevoli.", "原批次已通过权威回执解决。");
            RecoveryText(catalog, "overlapPending", "Another import contains some of these rows. Wait for its confirmation, then reopen recovery. This original batch remains unresolved.", "Otra importación contiene algunas de estas filas. Espera su confirmación y vuelve a abrir la recuperación. Este lote original sigue sin resolver.", "Un altro import contiene alcune di queste righe. Attendi la sua conferma, poi riapri il recupero. Questo batch originale resta irrisolto.", "另一个导入包含其中部分行。请等待其确认后重新打开恢复。此原批次仍未解决。");
            RecoveryText(catalog, "historyConflict", "Admin confirms overlapping imports, but their price history cannot be matched safely. Keep the original batch and ask support to reconcile the original receipts and history.", "Admin confirma importaciones superpuestas, pero no se puede conciliar su historial de precios de forma segura. Conserva el lote original y solicita soporte con los recibos e historial originales.", "Admin conferma import sovrapposti, ma lo storico prezzi non può essere associato in sicurezza. Conserva il batch originale e richiedi assistenza per riconciliare ricevute e storico originali.", "Admin 已确认重叠导入，但无法安全匹配其价格历史。请保留原批次，并联系支持人员核对原始回执和历史记录。");
            RecoveryText(catalog, "receiptConflict", "The Admin receipt does not fully match this import. Recovery remains unresolved. Ask support to verify the receipt and product mappings.", "El recibo de Admin no coincide completamente con esta importación. La recuperación sigue sin resolver. Solicita soporte para verificar el recibo y los productos asociados.", "La ricevuta Admin non corrisponde completamente all’importazione. Il recupero resta irrisolto. Richiedi assistenza per verificare ricevuta e associazioni prodotti.", "Admin 回执与此导入不完全匹配。恢复仍未解决。请联系支持人员核对回执和商品映射。");
            RecoveryText(catalog, "productChanged", "The current product data is unavailable or has changed. Refresh the catalog and reopen recovery to verify the intended correction.", "Los datos actuales del producto no están disponibles o han cambiado. Actualiza el catálogo y vuelve a abrir la recuperación para verificar la corrección.", "I dati attuali del prodotto non sono disponibili o sono cambiati. Aggiorna il catalogo e riapri il recupero per verificare la correzione prevista.", "当前商品数据不可用或已更改。请刷新目录并重新打开恢复，检查预期修改。");
            RecoveryText(catalog, "awaitingAck", "Awaiting the replacement ACK. The original batch remains unresolved.", "Esperando el ACK del reemplazo. El lote original sigue sin resolver.", "In attesa dell’ACK della sostituzione. Il batch originale resta irrisolto.", "正在等待替代批次的 ACK，原批次仍未解决。");
            RecoveryText(catalog, "neverSent", "Durable evidence confirms this batch was never sent.", "La evidencia persistente confirma que este lote nunca se envió.", "La prova persistente conferma che questo batch non è mai stato inviato.", "持久证据确认此批次从未发送。");
            RecoveryText(catalog, "receipt.safe", "The original identity is safe to replace. All original rows will be retained.", "La identidad original puede reemplazarse de forma segura. Se conservarán todas las filas originales.", "L’identità originale può essere sostituita in sicurezza. Tutte le righe originali saranno conservate.", "原始标识可以安全替换。所有原始行均将保留。");
            RecoveryText(catalog, "receipt.accepted", "Admin accepted the original batch. Only changes to accepted values will be sent, preserving the receipt and history.", "Admin aceptó el lote original. Solo se enviarán cambios de valores aceptados, preservando el recibo y el historial.", "Admin ha accettato il batch originale. Verranno inviate solo le modifiche ai valori accettati, conservando ricevuta e storico.", "Admin 已接受原批次。将仅发送已接受值的修改，并保留回执和历史记录。");
            RecoveryText(catalog, "receipt.unknown", "Remote outcome unknown: an authoritative receipt is required before replacement.", "Resultado remoto desconocido: se requiere un recibo autoritativo antes del reemplazo.", "Esito remoto incerto: serve una ricevuta autorevole prima della sostituzione.", "远程结果未知：替换前需要权威回执。");
            RecoveryText(catalog, "unknownBlocked", "The remote outcome cannot be established safely. Keep this draft and retry verification after the Admin service is available.", "No se puede determinar el resultado remoto de forma segura. Conserva este borrador y reintenta la verificación cuando Admin esté disponible.", "Non è possibile stabilire l’esito remoto in sicurezza. Conserva la bozza e riprova la verifica quando Admin è disponibile.", "无法安全确定远程结果。请保留草稿，并在 Admin 服务可用后重试验证。");
            RecoveryText(catalog, "invalidData", "Import data must be corrected. Prices must be whole CLP amounts from 0 to 999,999,999.", "Hay que corregir los datos. Los precios deben ser importes enteros en CLP de 0 a 999.999.999.", "Correggi i dati dell’importazione. I prezzi devono essere importi interi CLP da 0 a 999.999.999.", "必须修改导入数据。价格必须为 0 到 999,999,999 之间的整数 CLP 金额。");
            RecoveryText(catalog, "invalidQuantity", "Use a quantity from 0 to 999,999,999 with at most 3 decimal places.", "Usa una cantidad de 0 a 999.999.999 con un máximo de 3 decimales.", "Inserisci una quantità da 0 a 999.999.999 con al massimo 3 decimali.", "请输入 0 到 999,999,999 之间的数量，最多保留 3 位小数。");
            RecoveryText(catalog, "quantityConflict", "This quantity correction cannot be applied safely to current stock. Review the original quantity, intended correction and current stock; your draft is retained.", "No se puede aplicar esta corrección de cantidad de forma segura al stock actual. Revisa la cantidad original, la corrección prevista y el stock actual; se conserva el borrador.", "Questa correzione di quantità non può essere applicata in sicurezza allo stock corrente. Verifica la quantità originale, la correzione prevista e lo stock corrente: la bozza è conservata.", "无法将此数量修改安全应用于当前库存。请检查原始数量、预期修改和当前库存；草稿已保留。");
            RecoveryText(catalog, "authentication", "Sign in with catalog import permission and a valid trusted device session, then retry.", "Inicia sesión con permiso para importar catálogo y una sesión de dispositivo confiable válida, y reintenta.", "Accedi con il permesso di importazione catalogo e una sessione dispositivo attendibile valida, poi riprova.", "请使用具有目录导入权限的账号和有效的受信设备会话登录，然后重试。");
            RecoveryText(catalog, "backupFailed", "The verified backup failed. No replacement was applied. Check the backup destination and retry; your draft is retained.", "Falló la copia verificada. No se aplicó el reemplazo. Comprueba el destino de la copia y reintenta; se conserva el borrador.", "Il backup verificato è fallito. Nessuna sostituzione applicata. Verifica la destinazione del backup e riprova: la bozza è conservata.", "已验证的备份失败。未应用替代批次。请检查备份目标并重试；草稿已保留。");
            RecoveryText(catalog, "saveFailed", "The local recovery could not be saved. Its changes were rolled back and your draft is retained. Retry; ask support if the problem persists.", "No se pudo guardar la recuperación local. Se revirtieron sus cambios y se conserva el borrador. Reintenta; solicita soporte si el problema persiste.", "Il recupero locale non è stato salvato. Le modifiche sono state annullate e la bozza è conservata. Riprova; richiedi assistenza se il problema persiste.", "无法保存本地恢复。相关修改已回滚，草稿已保留。请重试；如果问题仍然存在，请联系支持人员。");
            RecoveryText(catalog, "network", "Admin is unreachable or the response was lost. Your draft is retained; verify the receipt before retrying.", "Admin no está disponible o se perdió la respuesta. Se conserva el borrador; verifica el recibo antes de reintentar.", "Admin non è raggiungibile o la risposta è andata persa. La bozza è conservata: verifica la ricevuta prima di riprovare.", "Admin 无法连接或响应丢失。草稿已保留；重试前请验证回执。");
            RecoveryText(catalog, "conflict", "The shop, session, or original batch changed. Close this draft and reopen recovery in the correct shop.", "Cambió la tienda, la sesión o el lote original. Cierra este borrador y vuelve a abrir la recuperación en la tienda correcta.", "Negozio, sessione o batch originale sono cambiati. Chiudi la bozza e riapri il recupero nel negozio corretto.", "店铺、会话或原批次已更改。请关闭草稿，并在正确店铺重新打开恢复。");
            RecoveryText(catalog, "affectedField", "{0} · {1}: {2} (CLP 0–999,999,999)", "{0} · {1}: {2} (CLP 0–999.999.999)", "{0} · {1}: {2} (CLP 0–999.999.999)", "{0} · {1}：{2}（CLP 0–999,999,999）");
            RecoveryText(catalog, "rowError", "Row {0} · {1}: {2}", "Fila {0} · {1}: {2}", "Riga {0} · {1}: {2}", "第 {0} 行 · {1}：{2}");
            RecoveryText(catalog, "permission", "Catalog import permission is required to recover this batch.", "Se requiere permiso para importar catálogo y recuperar este lote.", "Serve il permesso di importazione catalogo per recuperare questo batch.", "恢复此批次需要目录导入权限。");
        }

        private static void RecoveryText(Dictionary<string, Dictionary<string, string>> catalog,
            string key, string en, string es, string it, string zh)
        {
            catalog["en"]["importRecovery." + key] = en;
            catalog["es"]["importRecovery." + key] = es;
            catalog["it"]["importRecovery." + key] = it;
            catalog["zh-CN"]["importRecovery." + key] = zh;
        }
    }
}
